<?xml version="1.0" encoding="utf-8"?><Database Name="PokerDataBase" Class="pokerDataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\PokerDataBase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="LinqToSql.Properties.Settings" SettingsPropertyName="PokerDataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tables" Member="Tables">
    <Type Name="Table">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentPlaying" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaxPlayers" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BigBlind" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Money" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>